### ISSUE TITLE
Script doesn't work

### ISSUE THREAD

**Issue by nbraud** [SnapperGee/pip_upgrade#1]
Tried as requested, fails to run on my system:

```
$ ./pipupgrade
./pipupgrade: line 297: declare: `': not a valid identifier
Updating outdated pip3 packages...

Package         Version Latest Type 
--------------- ------- ------ -----
flake8          3.7.7   3.7.8  wheel
ipython         7.5.0   7.6.1  wheel
isort           4.3.20  4.3.21 wheel
pydocstyle      3.0.0   4.0.0  wheel
snowballstemmer 1.2.1   1.9.0  sdist

./pipupgrade: line 320: 'debug': syntax error: operand expected (error token is "'debug'")
```

**Comment by SnapperGee** [comment]
@nbraud 
Is your current Bash version 3.4 or greater?

**Comment by SnapperGee** [comment]
Arrays that held various cli option arguments were in an unreachable scope. Arrays have now been moved to main() function's scope mitigating issue. Thanks!

**Comment by SnapperGee** [comment]
Arrays that held various cli option arguments were in an unreachable scope. Arrays have now been moved to main() function's scope mitigating issue. Thanks!
--
